# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 252f5215cdaea175ae36ae48ee440c4fb0d71ede4574786daf29bd1e84e0dd27d1f656ea217724560e61dd8cc2d55e56e0b0c740bc789d1fe77f504ffe1d8614

test:
  secret_key_base: 07519b62e1aadf4f74d89dd25a83ac61824241e7eb1b8813b969e446a38c52ecb30f395cf891ac9ccb319557122becc02d18b6cc6980345747d577f830c91a3d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
